services:

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: pw
    networks: 
      - app-network

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: mysql
    ports: 
      - "8080:80"
    depends_on: 
      - mysql
    networks: 
      - app-network

networks:
  app-network:
    driver: bridge